def add_args(parser):
    parser.add_argument('-embedding_size', type=int, default = 800,help="""Embedding size""")
    parser.add_argument('-rnn_size_sent', type=int, default = 300,help="""The number of units of unidirectional rnn of sentence encoder""")
    parser.add_argument('-rnn_size_matrix', type=int, default = 300,help="""The number of units of unidirectional rnn of matrix encoder""")
    parser.add_argument('-attn_dim_sent', type=int, default = 400,help="""The dim of the weight of sentence attention,d_a in the paper""")
    parser.add_argument('-attn_dim_matrix', type=int, default = 400,help="""The dim of the weight of matrix attention""")
    parser.add_argument('-num_feature', type=int, default = 15,help="""r in the paper""")
    parser.add_argument('-penalization_coe', type=float, default = 0.01,help="""multiplied by P""")
    parser.add_argument('-batch_size', type=int, default = 64)
    parser.add_argument('-learning_rate', type=float, default = 0.05)
    parser.add_argument('-epochs', type=int, default = 200)
    parser.add_argument('-checkpoint', type=str,default = None)
    parser.add_argument('-models_dir',type=str, default = 'models/',help="""the directory to save checkpoints""")
    parser.add_argument('-tiny',action='store_true')
    parser.add_argument('-use_gru',type=bool, default = False,help = """If false,use lstm for the encoder""")
    parser.add_argument('-test',action = 'store_true')
    parser.add_argument('-predict',action = 'store_true')
